AWSTemplateFormatVersion: 2010-09-09

Description: |
  Task Definition
  Fargate Service
  Execution Role
  Task Role

Parameters:
  NetworkingStack:
    Type: String
    Description: This is our base layer of networking components eg. VPC, Subnets
    Default: CrdNet

  ClusterStack:
    Type: String
    Description: This is our cluster layer eg ECS cluster
    Default: CrdCluster
  
  ContainerPort:
    Type: Number
    Default: 4567
    
  ContainerName:
    Type: String
    Default: backend-flask
  
  TaskFamily: 
    Type: String
    Default: backend-flask
  
  ServiceName:
    Type: String
    Default: backend-flask

  ServiceCpu:
    Type: String
    Default: '256'

  ServiceMemory:
    Type: String
    Default: '512'

  EcrImage:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cfn/cruddur/backend-flask/ECRImage

  EnvOtelServiceName:
    Type: String
    Default: backend-flask

  EnvOtelExporterOtlpEndpoint:
    Type: String
    Default: https://api.honeycomb.io

  EnvAWSCognitoUserPoolId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cfn/cruddur/backend-flask/EnvAWSCognitoUserPoolId

  EnvCognitoUserPoolClientId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/cfn/cruddur/backend-flask/EnvCognitoUserPoolClientId'

  EnvFrontendUrl:
    Type: String

  EnvNewFrontendUrl:
    Type: String
    
  EnvTestFrontendUrl:
    Type: String

  EnvBackendUrl:
    Type: String

  FlaskEnv:
    Type: String
    Default: "production"

  SecretsAWSAccessKeyId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cfn/cruddur/backend-flask/SecretsAWSAccessKeyId

  SecretsSecretAccessKey:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cfn/cruddur/backend-flask/SecretsSecretAccessKey

  SecretsConnectionUrl:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cfn/cruddur/backend-flask/SecretsConnectionUrl

  SecretsRollbarAccessToken:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cfn/cruddur/backend-flask/SecretsRollbarAccessToken

  SecretsOtelExporterOltpHeaders:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cfn/cruddur/backend-flask/SecretsOtelExporterOltpHeaders

  DDBMessageTable:
    Type: String
    Default: cruddur-messages

Resources:
  
  FargateService:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Fn::ImportValue:
          !Sub "${ClusterStack}ClusterName"
      DeploymentController: 
        Type: ECS
      DesiredCount: 1
      EnableECSManagedTags: true
      EnableExecuteCommand: true 
      HealthCheckGracePeriodSeconds: 0
      LaunchType: FARGATE
      LoadBalancers:
        - TargetGroupArn:
            Fn::ImportValue:
              !Sub "${ClusterStack}BackendTGArn"
          ContainerName: !Ref ContainerName
          ContainerPort: !Ref ContainerPort
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - Fn::ImportValue:
                !Sub "${ClusterStack}ServiceSecurityGroupId"
          Subnets:
            Fn::Split:
              - ","
              - Fn::ImportValue:
                  !Sub "${NetworkingStack}PublicSubnetIds"
      PlatformVersion: LATEST
      PropagateTags: SERVICE
      ServiceConnectConfiguration:
        Enabled: true

        Namespace: "cruddur"
        # log config 
        Services:
          - DiscoveryName: backend-flask
            PortName: backend-flask
            ClientAliases:
              - Port: !Ref ContainerPort
            
      # ServiceRegistries:
      #   - RegistryArn: !Sub 'arn:aws:servicediscovery:${AWS::Region}:${AWS::AccountId}:service/srv-cruddur-backend-flask'
      #     Port: !Ref ContainerPort
      #     ContainerName: !Ref ContainerName
      #     ContainerPort: !Ref ContainerPort

      ServiceName: !Ref ServiceName
      TaskDefinition: !Ref TaskDefinition

  TaskDefinition:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html
      Type: 'AWS::ECS::TaskDefinition'
      Properties:
        Family: !Ref TaskFamily
        ExecutionRoleArn: !GetAtt ExecutionRole.Arn
        TaskRoleArn: !GetAtt TaskRole.Arn
        NetworkMode: 'awsvpc'
        Cpu: !Ref ServiceCpu
        Memory: !Ref ServiceMemory
        RequiresCompatibilities:
          - 'FARGATE'
        ContainerDefinitions:
          - Name: 'xray'
            Image: 'public.ecr.aws/xray/aws-xray-daemon'
            Essential: true
            User: '1337'
            PortMappings:
              - Name: 'xray'
                ContainerPort: 2000
                Protocol: 'udp'
          - Name: 'backend-flask'
            Image: !Ref EcrImage 
            Essential: true
            HealthCheck:
              Command:
                - 'CMD-SHELL'
                - 'python /backend-flask/bin/health-check'
              Interval: 30
              Timeout: 6
              Retries: 3
              StartPeriod: 60
            PortMappings:
              - Name: !Ref ContainerName
                ContainerPort: !Ref ContainerPort
                Protocol: 'tcp'
                AppProtocol: 'http'
            LogConfiguration:
              LogDriver: 'awslogs'
              Options:
                awslogs-group: 'cruddur'
                awslogs-region: !Ref AWS::Region
                awslogs-stream-prefix: !Ref ServiceName
            Environment:
              - Name: FLASK_ENV
                Value: !Ref FlaskEnv
              - Name: 'OTEL_SERVICE_NAME'
                Value: !Ref EnvOtelServiceName
              - Name: 'OTEL_EXPORTER_OTLP_ENDPOINT'
                Value: !Ref EnvOtelExporterOtlpEndpoint
              - Name: 'FRONTEND_URL'
                Value: !Ref EnvFrontendUrl
              - Name: 'NEW_FRONTEND_URL'
                Value: !Ref EnvNewFrontendUrl
              - Name: 'TEST_FRONTEND_URL'
                Value: !Ref EnvTestFrontendUrl
              - Name: 'BACKEND_URL'
                Value: !Ref EnvBackendUrl
              - Name: 'AWS_DEFAULT_REGION'
                Value: !Ref AWS::Region
              - Name: DDB_MESSAGE_TABLE
                Value: !Ref DDBMessageTable
            Secrets:
              - Name: 'AWS_ACCESS_KEY_ID'
                ValueFrom: !Ref SecretsAWSAccessKeyId
              - Name: 'AWS_SECRET_ACCESS_KEY'
                ValueFrom: !Ref SecretsSecretAccessKey
              - Name: 'CONNECTION_URL'
                ValueFrom: !Ref SecretsConnectionUrl
              - Name: 'ROLLBAR_ACCESS_TOKEN'
                ValueFrom: !Ref SecretsRollbarAccessToken
              - Name: 'OTEL_EXPORTER_OTLP_HEADERS'
                ValueFrom: !Ref SecretsOtelExporterOltpHeaders
              - Name: 'AWS_COGNITO_USER_POOL_ID'
                ValueFrom: !Ref EnvAWSCognitoUserPoolId
              - Name: 'AWS_COGNITO_USER_POOL_CLIENT_ID'
                ValueFrom: !Ref EnvCognitoUserPoolClientId

  ExecutionRole:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
    Type: AWS::IAM::Role
    Properties:
      RoleName: CruddurServiceExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'ecs-tasks.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'cruddur-execution-policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: 'VisualEditor0'
                Effect: 'Allow'
                Action:
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
              - Sid: 'VisualEditor1'
                Effect: 'Allow'
                Action:
                  - 'ssm:GetParameters'
                  - 'ssm:GetParameter'
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cruddur/${ServiceName}/*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

  TaskRole:
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
      Type: AWS::IAM::Role
      Properties:
        RoleName: CruddurServiceTaskRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Principal:
                Service: 'ecs-tasks.amazonaws.com'
              Action: 'sts:AssumeRole'
        Policies:
          - PolicyName: 'cruddur-task-policy'
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Sid: 'VisualEditor0'
                  Effect: 'Allow'
                  Action:
                    - ssmmessages:CreateControlChannel
                    - ssmmessages:CreateDataChannel
                    - ssmmessages:OpenControlChannel
                    - ssmmessages:OpenDataChannel
                  Resource: '*'
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
          - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
  
Outputs:
  ServiceName:
    Value: !GetAtt FargateService.Name
    Export:
      Name: !Sub "${AWS::StackName}ServiceName"