tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT

  - name: postgres
    before: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev

    command: |
      export GITPOD_IP=$(curl ifconfig.me)
      cd "$THEIA_WORKSPACE_ROOT"
      source "./bin/rds/update-sg-rule"
      ruby "./bin/frontend/generate-env"
      ruby "./bin/backend/generate-env"
      exit

  - name: npm-install
    before: |
      cd "$THEIA_WORKSPACE_ROOT/frontend-react-js"
      npm i
      exit
    # source "$THEIA_WORKSPACE_ROOT/frontend-react-js/bin/auto-redirect"

  - name: python-package-install
    before: |
      cd "$THEIA_WORKSPACE_ROOT/backend-flask"
      pip3 install --upgrade pip
      pip3 install -r requirements.txt
      exit

  - name: fargate
    before: |
      curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      sudo dpkg -i session-manager-plugin.deb
      sudo rm session-manager-plugin.deb
      exit

  - name: cdk
    before: |
      npm install aws-cdk -g
      cd thumbing-serverless-cdk
      cp .env.example .env
      npm i
      exit

vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - cweijan.vscode-postgresql-client2

# To open ports automatically
ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    visibility: public
  # - name: xray-daemon
  #   port: 2000
  #   visibility: public
  # - name: otel-collector
  #   port: 4318
  #   visibility: public
  - name: psql
    port: 5432
    visibility: public
  - name: ddb
    port: 8000
    visibility: public
