version: "3.8"
services:
  backend-flask:
    environment:
      FRONTEND_URL: "https://3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      
      #jwt verification
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
      AWS_COGNITO_USER_POOL_ID: "${AWS_USER_POOLS_ID}"
      AWS_COGNITO_USER_POOL_CLIENT_ID: "${CLIENT_ID}"

      # # openTelemetry
      # OTEL_SERVICE_NAME: "backend-flask"
      # OTEL_EXPORTER_OTLP_ENDPOINT: "https://api.honeycomb.io"
      # OTEL_EXPORTER_OTLP_HEADERS: "x-honeycomb-team=${HONEYCOMB_API_KEY}"

      # # AWS XRAY
      # AWS_XRAY_URL: "*4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}*"
      # AWS_XRAY_DAEMON_ADDRESS: "xray-daemon:2000"
      # # watchtower - cloudwatch
      # AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
      # AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      # AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"

      # # Rollbar
      # ROLLBAR_ACCESS_TOKEN: "${ROLLBAR_ACCESS_TOKEN}"

    build: ./backend-flask
    ports:
      - "4567:4567"

    healthcheck:
      test: curl --fail https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}/api/health || exit 1
      interval: 300s
      timeout: 10s
      start_period: 10s
      retries: 3

    volumes:
      - ./backend-flask:/backend-flask
    
  frontend-react-js:
    environment:
      REACT_APP_BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      REACT_APP_OTEL_COLLECTOR_URL: "https://4318-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
       # for cognito
      REACT_APP_AWS_PROJECT_REGION: "${AWS_DEFAULT_REGION}"
      REACT_APP_AWS_COGNITO_REGION: "${AWS_DEFAULT_REGION}"
      REACT_APP_AWS_USER_POOLS_ID: "${AWS_USER_POOLS_ID}"
      REACT_APP_CLIENT_ID: "${CLIENT_ID}"
      # ------------
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    healthcheck:
      test: curl --fail https://3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST} || exit 1
      interval: 300s
      timeout: 10s
      start_period: 10s
      retries: 3
    volumes:
      - ./frontend-react-js:/frontend-react-js

  # # OTEL Collector
  # otel-collector:
  #   environment:
  #      HONEYCOMB_API_KEY: "${HONEYCOMB_API_KEY}"
  #      FRONTEND_URL_WITHOUT_HTTP: "3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
  #   image: otel/opentelemetry-collector
  #   command: [--config=/etc/otel-collector-config.yaml]
  #   volumes:
  #     - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
  #   ports:
  #     - 4318:4318 # OTLP http receiver
  
  # xray-daemon:
  #   image: "amazon/aws-xray-daemon"
  #   environment:
  #     AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  #     AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  #     AWS_REGION: "us-east-1"
  #   command:
  #     - "xray -o -b xray-daemon:2000"
  #   ports:
  #     - 2000:2000/udp
  

# the name flag is a hack to change the default prepend folder
# name when outputting the image names
networks: 
  internal-network:
    driver: bridge
    name: cruddur
