name: Sync-Prod-Frontend

on:
  push:
    branches:
      - prod
    paths:
      - "frontend-react-js/**"
  pull_request:
    branches:
      - prod
    paths:
      - "frontend-react-js/**"

jobs:
  build_and_deploy:
    name: Statically build and deploy
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    steps:
      - name: checkout branch
        uses: actions/checkout@v3
      - run: cd frontend-react-js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/CrdSyncRole-Role-15HSTGN6QSC9D
          aws-region: ${{ secrets.REGION }}
          role-duration-seconds: 600
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.150.0
        with:
          ruby-version: "3.0"
          bundler-cache: true
      - run: cd ..
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake sync
